export const APP_USER_ERROR = {
  USER_INACTIVATED: "USER_INACTIVATED", //Tài khoản đã bị khóa,
  INVALID_CHAIN_ID: "INVALID_CHAIN_ID", // sai mạng
  INVALID_SIGNER: "INVALID_SIGNER", // sai nguời ký,
  UNKNOW_ERROR: "UNKNOW_ERROR",
}

export const MARKET_ERROR = {
  EXISTING_TXHASH: "EXISTING_TXHASH",
  INVALID_SENDER: "INVALID_SENDER",
  INVALID_RECEIVER: "INVALID_RECEIVER",
  TX_NOT_FOUND: "TX_NOT_FOUND",
}

export const ACCOUNT_STATUS = {
  ACTIVE: 1,
  BLOCK: 0,
}